### ISSUE TITLE
Upcoming changes for the next release

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-matlab#562]
The next release will happen shortly after the release of BIDS 1.9.

## Planned changes

Note that the change of branches name and workflow may break some users code if they were used to checking out the `dev` branch rather than `master`.

### Renaming of the default branch

Will be changed from `master` to `main`.

#### TODO

- [x] update CI branch names
- [x] update doc
- [x] changing to MIT license to be more in line with other BIDS tools in the main BIDS orga

### Changes from a git-flow to a more typical CI/CD

- `dev` branch will deleted.
- bug hot fixes and new features will both be merged into `main`

#### Reason:

- too much maintenance hassle for little benefit

#### TODO

- [x] update decision making
- [x] update contribution documentation

### Release schedule

Minimum will be to have a new version out for each new version of the BIDS specification to allow for a support of new BIDS datatypes or features. This should at least give a "clear" answer on how to organize releases.

**Comment by Remi-Gau** [comment]
@gllmflndn @nbeliy @ChristophePhillips @robertoostenveld @HenkMutsaerts 

Pinging people who I think should know about this.

Will update the top message if there is push-back or more suggestions on this.

**Comment by nbeliy** [comment]
If understand, the `main` now will be development and release branches?

As TODO, one think that could be added it's saving/loading/updating bids-matlab structure the initialization of dataset is quite slow, and it can be beneficial to initialize one and then load it from memory, but it can break the path reconstructions (depending how they are constructed). If needed, I can make a separate issue/suggestion.

**Comment by Remi-Gau** [comment]
> If understand, the `main` now will be development and release branches?

Yes. If you want the latest changes you just pull from main. 

If you want something "stable" then you have to pull a specific tag. 

If user run into a bug on a stable version then we could: 
- ask them to update to a newer version where this may have been fixed
- try the version from main if it is fixed there but we did not cut a new release 
- we fix the bug, merge the fix in main, make a minor release (ideally) 

> As TODO, one think that could be added it's saving/loading/updating bids-matlab structure the initialization of dataset is quite slow, and it can be beneficial to initialize one and then load it from memory, but it can break the path reconstructions (depending how they are constructed). If needed, I can make a separate issue/suggestion.

I think this is issue #320. So we can elaborate there. 

This has definitely been needed for a while though the ability to index only some subjects or sessions of a dataset can speed things up for some pipelines as you can index only those you will process. 

In any case I can add this issue to the milestone for the next release but as most of the things listed there I would consider more as nice to have, if we get something together in time rather than something blocking a release. 

https://github.com/bids-standard/bids-matlab/milestone/1

**Comment by Remi-Gau** [comment]
Forgot to tag @CPernet.

If you think of anyone else please tag them.

**Comment by gllmflndn** [comment]
+1 on branch renaming and simpler workflow.

**Comment by CPernet** [comment]
main and releases is easier to maintain than zillions of branches (although making releases it not fun) +1

**Comment by Remi-Gau** [comment]
Adding another change to the TODO: 
- [ ] changing to MIT license to be more in line with other BIDS tools in the main BIDS orga

@gllmflndn @CPernet @nbeliy

**Comment by Remi-Gau** [comment]
A new BIDS release is on the way for the end of the week. So I will make the changes listed in this issue after and make a new BIDS matlab release after this.

**Comment by gllmflndn** [comment]
:thumbsup: for the change of license from GPL to MIT.

Thank you @Remi-Gau for all the effort you've put into the upcoming release.

**Comment by CPernet** [comment]
sure, MIT is fine - our US friends need that, thx Remi

**Comment by Remi-Gau** [comment]
To rename your local master to main

May need to whatever you called the upstream remote.

```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by Remi-Gau** [comment]
OK all of those are done so I am closing.

Will mop up one thing or 2 and make a github release: should be picked up and released the file exchange too
https://nl.mathworks.com/matlabcentral/fileexchange/93740-bids-matlab
