### ISSUE TITLE
setting a first "developpers" meeting

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-matlab#59]
I think we need to establish some "ground rules" how to make this repo functions because I am growing less comfortable playing the benevolent dictator and also we should talk make some decisions about the overall architecture before we move further (for example see #39 and #19).

Also this might good occasion to let a couple of people (who have also written some matlab/octave code to deal with BIDS)  know about this repo, so they can think about bringing some of it here.

@gllmflndn @robertoostenveld @apjanke @tanguyduval 

I can set up a doodle to find a date in the coming weeks if you send me a way to contact you here : `remi dot gau at gmail dot com`.

Let me know your time zone too.

----
### TODO

- [x] open mattermost channel and update README
- [x] upload meeting video on G drive
- [x] update meeting notes
- [x] share outcomes on bids mailing list, mattermost town square, neurostars, twitter
- [x] open issue to collect "needs" / "requests" for bids-matlab
- [x] call to the community for already existing code for matlab / octave to deal with BIDS
- [x] doodle for next meeting
- [x] set up "governance" proposal for the repo

----

**Comment by robertoostenveld** [comment]
Yes, that is a good idea for expressing our ideas on what this repo/toolbox should aim at and how to work on it.

I have sent you an email with my timezone and email address.

**Comment by CPernet** [comment]
yep need to merge some the low level functions i created for eeglab bids-tools @arnodelorme

**Comment by CPernet** [comment]
some of my stuff also rely in [JSONio](https://github.com/gllmflndn/JSONio) from @gllmflndn we need to pull it again and/or find a way to keep it updated

**Comment by tanguyduval** [comment]
@Remi-Gau thank you for adding me in the loop but I'm not working in Neuroimaging anymore ;) 
Great initiative though! 
Best

**Comment by apjanke** [comment]
I'm interested in participating in this. You can reach me at floss@apjanke.net.

**Comment by arnodelorme** [comment]
We have developed this other repo https://github.com/sccn/bids-matlab-tools which is specialized in converting EEGLAB datasets and EEGLAB STUDY to BIDS. I have tried the current repo, and it would be possible to use it as low-level conversion for our own effort. The incentive is low though (why break something that works), but if somebody was motivated, why not. Happy to contribute in any way I can. Cheers

**Comment by Remi-Gau** [comment]
> We have developed this other repo https://github.com/sccn/bids-matlab-tools which is specialized in converting EEGLAB datasets and EEGLAB STUDY to BIDS. I have tried the current repo, and it would be possible to use it as low-level conversion for our own effort. The incentive is low though (why break something that works), but if somebody was motivated, why not. Happy to contribute in any way I can. Cheers

We'll send a doodle so we can all meet and chat.

I don't think anyone wants to break things for sure. :smile: 

But if anything you have done can be reinjected in here to be "abstracted" from its original tool so that it can be reused more globally, thay might save some efforts in the long run.

**Comment by CPernet** [comment]
@arnodelorme some functions can be moved straigth away - eg
https://github.com/sccn/bids-matlab-tools/blob/master/rename_brainvision_files.m
https://github.com/sccn/bids-matlab-tools/blob/master/bids_spreadsheet2participants.m

**Comment by Remi-Gau** [comment]
Mattermost channel as been created: https://mattermost.brainhack.org/brainhack/channels/bids-matlab

Added the link on the README of the repo

**Comment by Remi-Gau** [comment]
Minutes notes from the meeting (writing is work in progress):

https://docs.google.com/document/d/1nnquTdeVKo5d0-oTScEyMRRJFQTAlSz9g7yG7SsbR1w/edit?usp=sharing
